### ISSUE TITLE
Module Import Error

### ISSUE THREAD

**Issue by drwatsoncode** [shagabutdinov/sublime-shell-status#1]
I seem to be having a very obvious problem, so I assume I'm doing something wrong. 
When sublime loads (or reloads) the **ShellStatus** plugin, I get an error when importing StatusMessage. 
I.e.   the line `from StatusMessage import status_message` throws an **ImportError** exception with the message `No module named StatusMessage`.
I did install the prerequisite package **StatusMessage**. At first, it had an error with trailing commas in the keybindings file, but I corrected that. Now there are no errors when **StatusMessage** loads (or reloads) but I still cannot import it, even using Sublime's python interpreter (e.g. by entering `from StatusMessage import status_message`)
It seems like this is probably a configuration error in my setup etc. What could be going wrong, and how can I troubleshoot this?
Thanks!

**Comment by shagabutdinov** [comment]
Probably, this plugin could be installed under different name; try to do "ls" on your packages folder and see if the plugin has "StatusMessage" name but not "sublime-shell-status". Also check "status_message.py" file in package folder. 

If it does not help try to save "status_message.py" file to trigger sublime plugin reload and see console for errors. If there is any, report here I'll try to fix it.

**Comment by shagabutdinov** [comment]
I close it as outdated. Please, reopen if issue still remains.
